// Code generated by BobGen psql v0.34.2. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"encoding/json"
	"testing"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/jaswdr/faker/v2"
	"github.com/lib/pq"
	models "github.com/mbvlabs/grafto/models_new/internal/models"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/types"
)

type RiverJobMod interface {
	Apply(*RiverJobTemplate)
}

type RiverJobModFunc func(*RiverJobTemplate)

func (f RiverJobModFunc) Apply(n *RiverJobTemplate) {
	f(n)
}

type RiverJobModSlice []RiverJobMod

func (mods RiverJobModSlice) Apply(n *RiverJobTemplate) {
	for _, f := range mods {
		f.Apply(n)
	}
}

// RiverJobTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type RiverJobTemplate struct {
	ID           func() int64
	State        func() RiverJobState
	Attempt      func() int16
	MaxAttempts  func() int16
	AttemptedAt  func() null.Val[time.Time]
	CreatedAt    func() time.Time
	FinalizedAt  func() null.Val[time.Time]
	ScheduledAt  func() time.Time
	Priority     func() int16
	Args         func() types.JSON[json.RawMessage]
	AttemptedBy  func() null.Val[pq.StringArray]
	Errors       func() null.Val[pq.StringArray]
	Kind         func() string
	Metadata     func() types.JSON[json.RawMessage]
	Queue        func() string
	Tags         func() pq.StringArray
	UniqueKey    func() null.Val[[]byte]
	UniqueStates func() null.Val[string]

	f *Factory
}

// Apply mods to the RiverJobTemplate
func (o *RiverJobTemplate) Apply(mods ...RiverJobMod) {
	for _, mod := range mods {
		mod.Apply(o)
	}
}

// toModel returns an *models.RiverJob
// this does nothing with the relationship templates
func (o RiverJobTemplate) toModel() *models.RiverJob {
	m := &models.RiverJob{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.State != nil {
		m.State = o.State()
	}
	if o.Attempt != nil {
		m.Attempt = o.Attempt()
	}
	if o.MaxAttempts != nil {
		m.MaxAttempts = o.MaxAttempts()
	}
	if o.AttemptedAt != nil {
		m.AttemptedAt = o.AttemptedAt()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.FinalizedAt != nil {
		m.FinalizedAt = o.FinalizedAt()
	}
	if o.ScheduledAt != nil {
		m.ScheduledAt = o.ScheduledAt()
	}
	if o.Priority != nil {
		m.Priority = o.Priority()
	}
	if o.Args != nil {
		m.Args = o.Args()
	}
	if o.AttemptedBy != nil {
		m.AttemptedBy = o.AttemptedBy()
	}
	if o.Errors != nil {
		m.Errors = o.Errors()
	}
	if o.Kind != nil {
		m.Kind = o.Kind()
	}
	if o.Metadata != nil {
		m.Metadata = o.Metadata()
	}
	if o.Queue != nil {
		m.Queue = o.Queue()
	}
	if o.Tags != nil {
		m.Tags = o.Tags()
	}
	if o.UniqueKey != nil {
		m.UniqueKey = o.UniqueKey()
	}
	if o.UniqueStates != nil {
		m.UniqueStates = o.UniqueStates()
	}

	return m
}

// toModels returns an models.RiverJobSlice
// this does nothing with the relationship templates
func (o RiverJobTemplate) toModels(number int) models.RiverJobSlice {
	m := make(models.RiverJobSlice, number)

	for i := range m {
		m[i] = o.toModel()
	}

	return m
}

// setModelRels creates and sets the relationships on *models.RiverJob
// according to the relationships in the template. Nothing is inserted into the db
func (t RiverJobTemplate) setModelRels(o *models.RiverJob) {}

// BuildSetter returns an *models.RiverJobSetter
// this does nothing with the relationship templates
func (o RiverJobTemplate) BuildSetter() *models.RiverJobSetter {
	m := &models.RiverJobSetter{}

	if o.ID != nil {
		m.ID = omit.From(o.ID())
	}
	if o.State != nil {
		m.State = omit.From(o.State())
	}
	if o.Attempt != nil {
		m.Attempt = omit.From(o.Attempt())
	}
	if o.MaxAttempts != nil {
		m.MaxAttempts = omit.From(o.MaxAttempts())
	}
	if o.AttemptedAt != nil {
		m.AttemptedAt = omitnull.FromNull(o.AttemptedAt())
	}
	if o.CreatedAt != nil {
		m.CreatedAt = omit.From(o.CreatedAt())
	}
	if o.FinalizedAt != nil {
		m.FinalizedAt = omitnull.FromNull(o.FinalizedAt())
	}
	if o.ScheduledAt != nil {
		m.ScheduledAt = omit.From(o.ScheduledAt())
	}
	if o.Priority != nil {
		m.Priority = omit.From(o.Priority())
	}
	if o.Args != nil {
		m.Args = omit.From(o.Args())
	}
	if o.AttemptedBy != nil {
		m.AttemptedBy = omitnull.FromNull(o.AttemptedBy())
	}
	if o.Errors != nil {
		m.Errors = omitnull.FromNull(o.Errors())
	}
	if o.Kind != nil {
		m.Kind = omit.From(o.Kind())
	}
	if o.Metadata != nil {
		m.Metadata = omit.From(o.Metadata())
	}
	if o.Queue != nil {
		m.Queue = omit.From(o.Queue())
	}
	if o.Tags != nil {
		m.Tags = omit.From(o.Tags())
	}
	if o.UniqueKey != nil {
		m.UniqueKey = omitnull.FromNull(o.UniqueKey())
	}
	if o.UniqueStates != nil {
		m.UniqueStates = omitnull.FromNull(o.UniqueStates())
	}

	return m
}

// BuildManySetter returns an []*models.RiverJobSetter
// this does nothing with the relationship templates
func (o RiverJobTemplate) BuildManySetter(number int) []*models.RiverJobSetter {
	m := make([]*models.RiverJobSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.RiverJob
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use RiverJobTemplate.Create
func (o RiverJobTemplate) Build() *models.RiverJob {
	m := o.toModel()
	o.setModelRels(m)

	return m
}

// BuildMany returns an models.RiverJobSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use RiverJobTemplate.CreateMany
func (o RiverJobTemplate) BuildMany(number int) models.RiverJobSlice {
	m := make(models.RiverJobSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableRiverJob(m *models.RiverJobSetter) {
	if m.MaxAttempts.IsUnset() {
		m.MaxAttempts = omit.From(random_int16(nil))
	}
	if m.Args.IsUnset() {
		m.Args = omit.From(random_types_JSON_json_RawMessage_(nil))
	}
	if m.Kind.IsUnset() {
		m.Kind = omit.From(random_string(nil))
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.RiverJob
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *RiverJobTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.RiverJob) (context.Context, error) {
	var err error

	return ctx, err
}

// Create builds a riverJob and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *RiverJobTemplate) Create(ctx context.Context, exec bob.Executor) (*models.RiverJob, error) {
	_, m, err := o.create(ctx, exec)
	return m, err
}

// MustCreate builds a riverJob and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *RiverJobTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.RiverJob {
	_, m, err := o.create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a riverJob and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *RiverJobTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.RiverJob {
	tb.Helper()
	_, m, err := o.create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// create builds a riverJob and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// this returns a context that includes the newly inserted model
func (o *RiverJobTemplate) create(ctx context.Context, exec bob.Executor) (context.Context, *models.RiverJob, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableRiverJob(opt)

	m, err := models.RiverJobs.Insert(opt).One(ctx, exec)
	if err != nil {
		return ctx, nil, err
	}
	ctx = riverJobCtx.WithValue(ctx, m)

	ctx, err = o.insertOptRels(ctx, exec, m)
	return ctx, m, err
}

// CreateMany builds multiple riverJobs and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o RiverJobTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.RiverJobSlice, error) {
	_, m, err := o.createMany(ctx, exec, number)
	return m, err
}

// MustCreateMany builds multiple riverJobs and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o RiverJobTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.RiverJobSlice {
	_, m, err := o.createMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple riverJobs and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o RiverJobTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.RiverJobSlice {
	tb.Helper()
	_, m, err := o.createMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// createMany builds multiple riverJobs and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// this returns a context that includes the newly inserted models
func (o RiverJobTemplate) createMany(ctx context.Context, exec bob.Executor, number int) (context.Context, models.RiverJobSlice, error) {
	var err error
	m := make(models.RiverJobSlice, number)

	for i := range m {
		ctx, m[i], err = o.create(ctx, exec)
		if err != nil {
			return ctx, nil, err
		}
	}

	return ctx, m, nil
}

// RiverJob has methods that act as mods for the RiverJobTemplate
var RiverJobMods riverJobMods

type riverJobMods struct{}

func (m riverJobMods) RandomizeAllColumns(f *faker.Faker) RiverJobMod {
	return RiverJobModSlice{
		RiverJobMods.RandomID(f),
		RiverJobMods.RandomState(f),
		RiverJobMods.RandomAttempt(f),
		RiverJobMods.RandomMaxAttempts(f),
		RiverJobMods.RandomAttemptedAt(f),
		RiverJobMods.RandomCreatedAt(f),
		RiverJobMods.RandomFinalizedAt(f),
		RiverJobMods.RandomScheduledAt(f),
		RiverJobMods.RandomPriority(f),
		RiverJobMods.RandomArgs(f),
		RiverJobMods.RandomAttemptedBy(f),
		RiverJobMods.RandomErrors(f),
		RiverJobMods.RandomKind(f),
		RiverJobMods.RandomMetadata(f),
		RiverJobMods.RandomQueue(f),
		RiverJobMods.RandomTags(f),
		RiverJobMods.RandomUniqueKey(f),
		RiverJobMods.RandomUniqueStates(f),
	}
}

// Set the model columns to this value
func (m riverJobMods) ID(val int64) RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.ID = func() int64 { return val }
	})
}

// Set the Column from the function
func (m riverJobMods) IDFunc(f func() int64) RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m riverJobMods) UnsetID() RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m riverJobMods) RandomID(f *faker.Faker) RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.ID = func() int64 {
			return random_int64(f)
		}
	})
}

// Set the model columns to this value
func (m riverJobMods) State(val RiverJobState) RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.State = func() RiverJobState { return val }
	})
}

// Set the Column from the function
func (m riverJobMods) StateFunc(f func() RiverJobState) RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.State = f
	})
}

// Clear any values for the column
func (m riverJobMods) UnsetState() RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.State = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m riverJobMods) RandomState(f *faker.Faker) RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.State = func() RiverJobState {
			return random_RiverJobState(f)
		}
	})
}

// Set the model columns to this value
func (m riverJobMods) Attempt(val int16) RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.Attempt = func() int16 { return val }
	})
}

// Set the Column from the function
func (m riverJobMods) AttemptFunc(f func() int16) RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.Attempt = f
	})
}

// Clear any values for the column
func (m riverJobMods) UnsetAttempt() RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.Attempt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m riverJobMods) RandomAttempt(f *faker.Faker) RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.Attempt = func() int16 {
			return random_int16(f)
		}
	})
}

// Set the model columns to this value
func (m riverJobMods) MaxAttempts(val int16) RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.MaxAttempts = func() int16 { return val }
	})
}

// Set the Column from the function
func (m riverJobMods) MaxAttemptsFunc(f func() int16) RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.MaxAttempts = f
	})
}

// Clear any values for the column
func (m riverJobMods) UnsetMaxAttempts() RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.MaxAttempts = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m riverJobMods) RandomMaxAttempts(f *faker.Faker) RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.MaxAttempts = func() int16 {
			return random_int16(f)
		}
	})
}

// Set the model columns to this value
func (m riverJobMods) AttemptedAt(val null.Val[time.Time]) RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.AttemptedAt = func() null.Val[time.Time] { return val }
	})
}

// Set the Column from the function
func (m riverJobMods) AttemptedAtFunc(f func() null.Val[time.Time]) RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.AttemptedAt = f
	})
}

// Clear any values for the column
func (m riverJobMods) UnsetAttemptedAt() RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.AttemptedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m riverJobMods) RandomAttemptedAt(f *faker.Faker) RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.AttemptedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			if f.Bool() {
				return null.FromPtr[time.Time](nil)
			}

			return null.From(random_time_Time(f))
		}
	})
}

// Set the model columns to this value
func (m riverJobMods) CreatedAt(val time.Time) RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m riverJobMods) CreatedAtFunc(f func() time.Time) RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m riverJobMods) UnsetCreatedAt() RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m riverJobMods) RandomCreatedAt(f *faker.Faker) RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m riverJobMods) FinalizedAt(val null.Val[time.Time]) RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.FinalizedAt = func() null.Val[time.Time] { return val }
	})
}

// Set the Column from the function
func (m riverJobMods) FinalizedAtFunc(f func() null.Val[time.Time]) RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.FinalizedAt = f
	})
}

// Clear any values for the column
func (m riverJobMods) UnsetFinalizedAt() RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.FinalizedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m riverJobMods) RandomFinalizedAt(f *faker.Faker) RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.FinalizedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			if f.Bool() {
				return null.FromPtr[time.Time](nil)
			}

			return null.From(random_time_Time(f))
		}
	})
}

// Set the model columns to this value
func (m riverJobMods) ScheduledAt(val time.Time) RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.ScheduledAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m riverJobMods) ScheduledAtFunc(f func() time.Time) RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.ScheduledAt = f
	})
}

// Clear any values for the column
func (m riverJobMods) UnsetScheduledAt() RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.ScheduledAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m riverJobMods) RandomScheduledAt(f *faker.Faker) RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.ScheduledAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m riverJobMods) Priority(val int16) RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.Priority = func() int16 { return val }
	})
}

// Set the Column from the function
func (m riverJobMods) PriorityFunc(f func() int16) RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.Priority = f
	})
}

// Clear any values for the column
func (m riverJobMods) UnsetPriority() RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.Priority = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m riverJobMods) RandomPriority(f *faker.Faker) RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.Priority = func() int16 {
			return random_int16(f)
		}
	})
}

// Set the model columns to this value
func (m riverJobMods) Args(val types.JSON[json.RawMessage]) RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.Args = func() types.JSON[json.RawMessage] { return val }
	})
}

// Set the Column from the function
func (m riverJobMods) ArgsFunc(f func() types.JSON[json.RawMessage]) RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.Args = f
	})
}

// Clear any values for the column
func (m riverJobMods) UnsetArgs() RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.Args = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m riverJobMods) RandomArgs(f *faker.Faker) RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.Args = func() types.JSON[json.RawMessage] {
			return random_types_JSON_json_RawMessage_(f)
		}
	})
}

// Set the model columns to this value
func (m riverJobMods) AttemptedBy(val null.Val[pq.StringArray]) RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.AttemptedBy = func() null.Val[pq.StringArray] { return val }
	})
}

// Set the Column from the function
func (m riverJobMods) AttemptedByFunc(f func() null.Val[pq.StringArray]) RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.AttemptedBy = f
	})
}

// Clear any values for the column
func (m riverJobMods) UnsetAttemptedBy() RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.AttemptedBy = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m riverJobMods) RandomAttemptedBy(f *faker.Faker) RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.AttemptedBy = func() null.Val[pq.StringArray] {
			if f == nil {
				f = &defaultFaker
			}

			if f.Bool() {
				return null.FromPtr[pq.StringArray](nil)
			}

			return null.From(random_pq_StringArray(f))
		}
	})
}

// Set the model columns to this value
func (m riverJobMods) Errors(val null.Val[pq.StringArray]) RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.Errors = func() null.Val[pq.StringArray] { return val }
	})
}

// Set the Column from the function
func (m riverJobMods) ErrorsFunc(f func() null.Val[pq.StringArray]) RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.Errors = f
	})
}

// Clear any values for the column
func (m riverJobMods) UnsetErrors() RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.Errors = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m riverJobMods) RandomErrors(f *faker.Faker) RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.Errors = func() null.Val[pq.StringArray] {
			if f == nil {
				f = &defaultFaker
			}

			if f.Bool() {
				return null.FromPtr[pq.StringArray](nil)
			}

			return null.From(random_pq_StringArray(f))
		}
	})
}

// Set the model columns to this value
func (m riverJobMods) Kind(val string) RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.Kind = func() string { return val }
	})
}

// Set the Column from the function
func (m riverJobMods) KindFunc(f func() string) RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.Kind = f
	})
}

// Clear any values for the column
func (m riverJobMods) UnsetKind() RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.Kind = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m riverJobMods) RandomKind(f *faker.Faker) RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.Kind = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m riverJobMods) Metadata(val types.JSON[json.RawMessage]) RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.Metadata = func() types.JSON[json.RawMessage] { return val }
	})
}

// Set the Column from the function
func (m riverJobMods) MetadataFunc(f func() types.JSON[json.RawMessage]) RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.Metadata = f
	})
}

// Clear any values for the column
func (m riverJobMods) UnsetMetadata() RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.Metadata = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m riverJobMods) RandomMetadata(f *faker.Faker) RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.Metadata = func() types.JSON[json.RawMessage] {
			return random_types_JSON_json_RawMessage_(f)
		}
	})
}

// Set the model columns to this value
func (m riverJobMods) Queue(val string) RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.Queue = func() string { return val }
	})
}

// Set the Column from the function
func (m riverJobMods) QueueFunc(f func() string) RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.Queue = f
	})
}

// Clear any values for the column
func (m riverJobMods) UnsetQueue() RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.Queue = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m riverJobMods) RandomQueue(f *faker.Faker) RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.Queue = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m riverJobMods) Tags(val pq.StringArray) RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.Tags = func() pq.StringArray { return val }
	})
}

// Set the Column from the function
func (m riverJobMods) TagsFunc(f func() pq.StringArray) RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.Tags = f
	})
}

// Clear any values for the column
func (m riverJobMods) UnsetTags() RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.Tags = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m riverJobMods) RandomTags(f *faker.Faker) RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.Tags = func() pq.StringArray {
			return random_pq_StringArray(f)
		}
	})
}

// Set the model columns to this value
func (m riverJobMods) UniqueKey(val null.Val[[]byte]) RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.UniqueKey = func() null.Val[[]byte] { return val }
	})
}

// Set the Column from the function
func (m riverJobMods) UniqueKeyFunc(f func() null.Val[[]byte]) RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.UniqueKey = f
	})
}

// Clear any values for the column
func (m riverJobMods) UnsetUniqueKey() RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.UniqueKey = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m riverJobMods) RandomUniqueKey(f *faker.Faker) RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.UniqueKey = func() null.Val[[]byte] {
			if f == nil {
				f = &defaultFaker
			}

			if f.Bool() {
				return null.FromPtr[[]byte](nil)
			}

			return null.From(random___byte(f))
		}
	})
}

// Set the model columns to this value
func (m riverJobMods) UniqueStates(val null.Val[string]) RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.UniqueStates = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m riverJobMods) UniqueStatesFunc(f func() null.Val[string]) RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.UniqueStates = f
	})
}

// Clear any values for the column
func (m riverJobMods) UnsetUniqueStates() RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.UniqueStates = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m riverJobMods) RandomUniqueStates(f *faker.Faker) RiverJobMod {
	return RiverJobModFunc(func(o *RiverJobTemplate) {
		o.UniqueStates = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			if f.Bool() {
				return null.FromPtr[string](nil)
			}

			return null.From(random_string(f))
		}
	})
}
