// Code generated by BobGen psql v0.34.2. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"encoding/json"
	"testing"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/jaswdr/faker/v2"
	models "github.com/mbvlabs/grafto/models_new/internal/models"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/types"
)

type RiverClientMod interface {
	Apply(*RiverClientTemplate)
}

type RiverClientModFunc func(*RiverClientTemplate)

func (f RiverClientModFunc) Apply(n *RiverClientTemplate) {
	f(n)
}

type RiverClientModSlice []RiverClientMod

func (mods RiverClientModSlice) Apply(n *RiverClientTemplate) {
	for _, f := range mods {
		f.Apply(n)
	}
}

// RiverClientTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type RiverClientTemplate struct {
	ID        func() string
	CreatedAt func() time.Time
	Metadata  func() types.JSON[json.RawMessage]
	PausedAt  func() null.Val[time.Time]
	UpdatedAt func() time.Time

	r riverClientR
	f *Factory
}

type riverClientR struct {
	RiverClientQueues []*riverClientRRiverClientQueuesR
}

type riverClientRRiverClientQueuesR struct {
	number int
	o      *RiverClientQueueTemplate
}

// Apply mods to the RiverClientTemplate
func (o *RiverClientTemplate) Apply(mods ...RiverClientMod) {
	for _, mod := range mods {
		mod.Apply(o)
	}
}

// toModel returns an *models.RiverClient
// this does nothing with the relationship templates
func (o RiverClientTemplate) toModel() *models.RiverClient {
	m := &models.RiverClient{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.Metadata != nil {
		m.Metadata = o.Metadata()
	}
	if o.PausedAt != nil {
		m.PausedAt = o.PausedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}

	return m
}

// toModels returns an models.RiverClientSlice
// this does nothing with the relationship templates
func (o RiverClientTemplate) toModels(number int) models.RiverClientSlice {
	m := make(models.RiverClientSlice, number)

	for i := range m {
		m[i] = o.toModel()
	}

	return m
}

// setModelRels creates and sets the relationships on *models.RiverClient
// according to the relationships in the template. Nothing is inserted into the db
func (t RiverClientTemplate) setModelRels(o *models.RiverClient) {
	if t.r.RiverClientQueues != nil {
		rel := models.RiverClientQueueSlice{}
		for _, r := range t.r.RiverClientQueues {
			related := r.o.toModels(r.number)
			for _, rel := range related {
				rel.RiverClientID = o.ID
				rel.R.RiverClient = o
			}
			rel = append(rel, related...)
		}
		o.R.RiverClientQueues = rel
	}
}

// BuildSetter returns an *models.RiverClientSetter
// this does nothing with the relationship templates
func (o RiverClientTemplate) BuildSetter() *models.RiverClientSetter {
	m := &models.RiverClientSetter{}

	if o.ID != nil {
		m.ID = omit.From(o.ID())
	}
	if o.CreatedAt != nil {
		m.CreatedAt = omit.From(o.CreatedAt())
	}
	if o.Metadata != nil {
		m.Metadata = omit.From(o.Metadata())
	}
	if o.PausedAt != nil {
		m.PausedAt = omitnull.FromNull(o.PausedAt())
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = omit.From(o.UpdatedAt())
	}

	return m
}

// BuildManySetter returns an []*models.RiverClientSetter
// this does nothing with the relationship templates
func (o RiverClientTemplate) BuildManySetter(number int) []*models.RiverClientSetter {
	m := make([]*models.RiverClientSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.RiverClient
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use RiverClientTemplate.Create
func (o RiverClientTemplate) Build() *models.RiverClient {
	m := o.toModel()
	o.setModelRels(m)

	return m
}

// BuildMany returns an models.RiverClientSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use RiverClientTemplate.CreateMany
func (o RiverClientTemplate) BuildMany(number int) models.RiverClientSlice {
	m := make(models.RiverClientSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableRiverClient(m *models.RiverClientSetter) {
	if m.ID.IsUnset() {
		m.ID = omit.From(random_string(nil))
	}
	if m.UpdatedAt.IsUnset() {
		m.UpdatedAt = omit.From(random_time_Time(nil))
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.RiverClient
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *RiverClientTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.RiverClient) (context.Context, error) {
	var err error

	if o.r.RiverClientQueues != nil {
		for _, r := range o.r.RiverClientQueues {
			var rel0 models.RiverClientQueueSlice
			ctx, rel0, err = r.o.createMany(ctx, exec, r.number)
			if err != nil {
				return ctx, err
			}

			err = m.AttachRiverClientQueues(ctx, exec, rel0...)
			if err != nil {
				return ctx, err
			}
		}
	}

	return ctx, err
}

// Create builds a riverClient and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *RiverClientTemplate) Create(ctx context.Context, exec bob.Executor) (*models.RiverClient, error) {
	_, m, err := o.create(ctx, exec)
	return m, err
}

// MustCreate builds a riverClient and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *RiverClientTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.RiverClient {
	_, m, err := o.create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a riverClient and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *RiverClientTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.RiverClient {
	tb.Helper()
	_, m, err := o.create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// create builds a riverClient and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// this returns a context that includes the newly inserted model
func (o *RiverClientTemplate) create(ctx context.Context, exec bob.Executor) (context.Context, *models.RiverClient, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableRiverClient(opt)

	m, err := models.RiverClients.Insert(opt).One(ctx, exec)
	if err != nil {
		return ctx, nil, err
	}
	ctx = riverClientCtx.WithValue(ctx, m)

	ctx, err = o.insertOptRels(ctx, exec, m)
	return ctx, m, err
}

// CreateMany builds multiple riverClients and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o RiverClientTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.RiverClientSlice, error) {
	_, m, err := o.createMany(ctx, exec, number)
	return m, err
}

// MustCreateMany builds multiple riverClients and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o RiverClientTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.RiverClientSlice {
	_, m, err := o.createMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple riverClients and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o RiverClientTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.RiverClientSlice {
	tb.Helper()
	_, m, err := o.createMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// createMany builds multiple riverClients and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// this returns a context that includes the newly inserted models
func (o RiverClientTemplate) createMany(ctx context.Context, exec bob.Executor, number int) (context.Context, models.RiverClientSlice, error) {
	var err error
	m := make(models.RiverClientSlice, number)

	for i := range m {
		ctx, m[i], err = o.create(ctx, exec)
		if err != nil {
			return ctx, nil, err
		}
	}

	return ctx, m, nil
}

// RiverClient has methods that act as mods for the RiverClientTemplate
var RiverClientMods riverClientMods

type riverClientMods struct{}

func (m riverClientMods) RandomizeAllColumns(f *faker.Faker) RiverClientMod {
	return RiverClientModSlice{
		RiverClientMods.RandomID(f),
		RiverClientMods.RandomCreatedAt(f),
		RiverClientMods.RandomMetadata(f),
		RiverClientMods.RandomPausedAt(f),
		RiverClientMods.RandomUpdatedAt(f),
	}
}

// Set the model columns to this value
func (m riverClientMods) ID(val string) RiverClientMod {
	return RiverClientModFunc(func(o *RiverClientTemplate) {
		o.ID = func() string { return val }
	})
}

// Set the Column from the function
func (m riverClientMods) IDFunc(f func() string) RiverClientMod {
	return RiverClientModFunc(func(o *RiverClientTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m riverClientMods) UnsetID() RiverClientMod {
	return RiverClientModFunc(func(o *RiverClientTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m riverClientMods) RandomID(f *faker.Faker) RiverClientMod {
	return RiverClientModFunc(func(o *RiverClientTemplate) {
		o.ID = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m riverClientMods) CreatedAt(val time.Time) RiverClientMod {
	return RiverClientModFunc(func(o *RiverClientTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m riverClientMods) CreatedAtFunc(f func() time.Time) RiverClientMod {
	return RiverClientModFunc(func(o *RiverClientTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m riverClientMods) UnsetCreatedAt() RiverClientMod {
	return RiverClientModFunc(func(o *RiverClientTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m riverClientMods) RandomCreatedAt(f *faker.Faker) RiverClientMod {
	return RiverClientModFunc(func(o *RiverClientTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m riverClientMods) Metadata(val types.JSON[json.RawMessage]) RiverClientMod {
	return RiverClientModFunc(func(o *RiverClientTemplate) {
		o.Metadata = func() types.JSON[json.RawMessage] { return val }
	})
}

// Set the Column from the function
func (m riverClientMods) MetadataFunc(f func() types.JSON[json.RawMessage]) RiverClientMod {
	return RiverClientModFunc(func(o *RiverClientTemplate) {
		o.Metadata = f
	})
}

// Clear any values for the column
func (m riverClientMods) UnsetMetadata() RiverClientMod {
	return RiverClientModFunc(func(o *RiverClientTemplate) {
		o.Metadata = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m riverClientMods) RandomMetadata(f *faker.Faker) RiverClientMod {
	return RiverClientModFunc(func(o *RiverClientTemplate) {
		o.Metadata = func() types.JSON[json.RawMessage] {
			return random_types_JSON_json_RawMessage_(f)
		}
	})
}

// Set the model columns to this value
func (m riverClientMods) PausedAt(val null.Val[time.Time]) RiverClientMod {
	return RiverClientModFunc(func(o *RiverClientTemplate) {
		o.PausedAt = func() null.Val[time.Time] { return val }
	})
}

// Set the Column from the function
func (m riverClientMods) PausedAtFunc(f func() null.Val[time.Time]) RiverClientMod {
	return RiverClientModFunc(func(o *RiverClientTemplate) {
		o.PausedAt = f
	})
}

// Clear any values for the column
func (m riverClientMods) UnsetPausedAt() RiverClientMod {
	return RiverClientModFunc(func(o *RiverClientTemplate) {
		o.PausedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m riverClientMods) RandomPausedAt(f *faker.Faker) RiverClientMod {
	return RiverClientModFunc(func(o *RiverClientTemplate) {
		o.PausedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			if f.Bool() {
				return null.FromPtr[time.Time](nil)
			}

			return null.From(random_time_Time(f))
		}
	})
}

// Set the model columns to this value
func (m riverClientMods) UpdatedAt(val time.Time) RiverClientMod {
	return RiverClientModFunc(func(o *RiverClientTemplate) {
		o.UpdatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m riverClientMods) UpdatedAtFunc(f func() time.Time) RiverClientMod {
	return RiverClientModFunc(func(o *RiverClientTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m riverClientMods) UnsetUpdatedAt() RiverClientMod {
	return RiverClientModFunc(func(o *RiverClientTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m riverClientMods) RandomUpdatedAt(f *faker.Faker) RiverClientMod {
	return RiverClientModFunc(func(o *RiverClientTemplate) {
		o.UpdatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

func (m riverClientMods) WithRiverClientQueues(number int, related *RiverClientQueueTemplate) RiverClientMod {
	return RiverClientModFunc(func(o *RiverClientTemplate) {
		o.r.RiverClientQueues = []*riverClientRRiverClientQueuesR{{
			number: number,
			o:      related,
		}}
	})
}

func (m riverClientMods) WithNewRiverClientQueues(number int, mods ...RiverClientQueueMod) RiverClientMod {
	return RiverClientModFunc(func(o *RiverClientTemplate) {
		related := o.f.NewRiverClientQueue(mods...)
		m.WithRiverClientQueues(number, related).Apply(o)
	})
}

func (m riverClientMods) AddRiverClientQueues(number int, related *RiverClientQueueTemplate) RiverClientMod {
	return RiverClientModFunc(func(o *RiverClientTemplate) {
		o.r.RiverClientQueues = append(o.r.RiverClientQueues, &riverClientRRiverClientQueuesR{
			number: number,
			o:      related,
		})
	})
}

func (m riverClientMods) AddNewRiverClientQueues(number int, mods ...RiverClientQueueMod) RiverClientMod {
	return RiverClientModFunc(func(o *RiverClientTemplate) {
		related := o.f.NewRiverClientQueue(mods...)
		m.AddRiverClientQueues(number, related).Apply(o)
	})
}

func (m riverClientMods) WithoutRiverClientQueues() RiverClientMod {
	return RiverClientModFunc(func(o *RiverClientTemplate) {
		o.r.RiverClientQueues = nil
	})
}
