// Code generated by BobGen psql v0.34.2. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

type Factory struct {
	baseGooseDBVersionMods   GooseDBVersionModSlice
	baseRiverClientMods      RiverClientModSlice
	baseRiverClientQueueMods RiverClientQueueModSlice
	baseRiverJobMods         RiverJobModSlice
	baseRiverLeaderMods      RiverLeaderModSlice
	baseRiverMigrationMods   RiverMigrationModSlice
	baseRiverQueueMods       RiverQueueModSlice
	baseTokenMods            TokenModSlice
	baseUserMods             UserModSlice
}

func New() *Factory {
	return &Factory{}
}

func (f *Factory) NewGooseDBVersion(mods ...GooseDBVersionMod) *GooseDBVersionTemplate {
	o := &GooseDBVersionTemplate{f: f}

	if f != nil {
		f.baseGooseDBVersionMods.Apply(o)
	}

	GooseDBVersionModSlice(mods).Apply(o)

	return o
}

func (f *Factory) NewRiverClient(mods ...RiverClientMod) *RiverClientTemplate {
	o := &RiverClientTemplate{f: f}

	if f != nil {
		f.baseRiverClientMods.Apply(o)
	}

	RiverClientModSlice(mods).Apply(o)

	return o
}

func (f *Factory) NewRiverClientQueue(mods ...RiverClientQueueMod) *RiverClientQueueTemplate {
	o := &RiverClientQueueTemplate{f: f}

	if f != nil {
		f.baseRiverClientQueueMods.Apply(o)
	}

	RiverClientQueueModSlice(mods).Apply(o)

	return o
}

func (f *Factory) NewRiverJob(mods ...RiverJobMod) *RiverJobTemplate {
	o := &RiverJobTemplate{f: f}

	if f != nil {
		f.baseRiverJobMods.Apply(o)
	}

	RiverJobModSlice(mods).Apply(o)

	return o
}

func (f *Factory) NewRiverLeader(mods ...RiverLeaderMod) *RiverLeaderTemplate {
	o := &RiverLeaderTemplate{f: f}

	if f != nil {
		f.baseRiverLeaderMods.Apply(o)
	}

	RiverLeaderModSlice(mods).Apply(o)

	return o
}

func (f *Factory) NewRiverMigration(mods ...RiverMigrationMod) *RiverMigrationTemplate {
	o := &RiverMigrationTemplate{f: f}

	if f != nil {
		f.baseRiverMigrationMods.Apply(o)
	}

	RiverMigrationModSlice(mods).Apply(o)

	return o
}

func (f *Factory) NewRiverQueue(mods ...RiverQueueMod) *RiverQueueTemplate {
	o := &RiverQueueTemplate{f: f}

	if f != nil {
		f.baseRiverQueueMods.Apply(o)
	}

	RiverQueueModSlice(mods).Apply(o)

	return o
}

func (f *Factory) NewToken(mods ...TokenMod) *TokenTemplate {
	o := &TokenTemplate{f: f}

	if f != nil {
		f.baseTokenMods.Apply(o)
	}

	TokenModSlice(mods).Apply(o)

	return o
}

func (f *Factory) NewUser(mods ...UserMod) *UserTemplate {
	o := &UserTemplate{f: f}

	if f != nil {
		f.baseUserMods.Apply(o)
	}

	UserModSlice(mods).Apply(o)

	return o
}

func (f *Factory) ClearBaseGooseDBVersionMods() {
	f.baseGooseDBVersionMods = nil
}

func (f *Factory) AddBaseGooseDBVersionMod(mods ...GooseDBVersionMod) {
	f.baseGooseDBVersionMods = append(f.baseGooseDBVersionMods, mods...)
}

func (f *Factory) ClearBaseRiverClientMods() {
	f.baseRiverClientMods = nil
}

func (f *Factory) AddBaseRiverClientMod(mods ...RiverClientMod) {
	f.baseRiverClientMods = append(f.baseRiverClientMods, mods...)
}

func (f *Factory) ClearBaseRiverClientQueueMods() {
	f.baseRiverClientQueueMods = nil
}

func (f *Factory) AddBaseRiverClientQueueMod(mods ...RiverClientQueueMod) {
	f.baseRiverClientQueueMods = append(f.baseRiverClientQueueMods, mods...)
}

func (f *Factory) ClearBaseRiverJobMods() {
	f.baseRiverJobMods = nil
}

func (f *Factory) AddBaseRiverJobMod(mods ...RiverJobMod) {
	f.baseRiverJobMods = append(f.baseRiverJobMods, mods...)
}

func (f *Factory) ClearBaseRiverLeaderMods() {
	f.baseRiverLeaderMods = nil
}

func (f *Factory) AddBaseRiverLeaderMod(mods ...RiverLeaderMod) {
	f.baseRiverLeaderMods = append(f.baseRiverLeaderMods, mods...)
}

func (f *Factory) ClearBaseRiverMigrationMods() {
	f.baseRiverMigrationMods = nil
}

func (f *Factory) AddBaseRiverMigrationMod(mods ...RiverMigrationMod) {
	f.baseRiverMigrationMods = append(f.baseRiverMigrationMods, mods...)
}

func (f *Factory) ClearBaseRiverQueueMods() {
	f.baseRiverQueueMods = nil
}

func (f *Factory) AddBaseRiverQueueMod(mods ...RiverQueueMod) {
	f.baseRiverQueueMods = append(f.baseRiverQueueMods, mods...)
}

func (f *Factory) ClearBaseTokenMods() {
	f.baseTokenMods = nil
}

func (f *Factory) AddBaseTokenMod(mods ...TokenMod) {
	f.baseTokenMods = append(f.baseTokenMods, mods...)
}

func (f *Factory) ClearBaseUserMods() {
	f.baseUserMods = nil
}

func (f *Factory) AddBaseUserMod(mods ...UserMod) {
	f.baseUserMods = append(f.baseUserMods, mods...)
}
