linters:
  disable-all: true
  enable:
    - bodyclose
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - sloglint
    - makezero
  # Enable presets.
  # https://golangci-lint.run/usage/linters
  # Default: []
  presets:
    - bugs
    # - comment
    # - complexity
    # - error
    # - format
    # - import
    # - metalinter
    # - module
    # - performance
    # - sql
    # - style
    # - test
    # - unused
  fast: false
