// Code generated by BobGen psql v0.34.2. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/lib/pq"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/types"
)

// Make sure the type GooseDBVersion runs hooks after queries
var _ bob.HookableType = &GooseDBVersion{}

// Make sure the type RiverClient runs hooks after queries
var _ bob.HookableType = &RiverClient{}

// Make sure the type RiverClientQueue runs hooks after queries
var _ bob.HookableType = &RiverClientQueue{}

// Make sure the type RiverJob runs hooks after queries
var _ bob.HookableType = &RiverJob{}

// Make sure the type RiverLeader runs hooks after queries
var _ bob.HookableType = &RiverLeader{}

// Make sure the type RiverMigration runs hooks after queries
var _ bob.HookableType = &RiverMigration{}

// Make sure the type RiverQueue runs hooks after queries
var _ bob.HookableType = &RiverQueue{}

// Make sure the type Token runs hooks after queries
var _ bob.HookableType = &Token{}

// Make sure the type User runs hooks after queries
var _ bob.HookableType = &User{}

// Make sure the type types.JSON[json.RawMessage] satisfies database/sql.Scanner
var _ sql.Scanner = (*types.JSON[json.RawMessage])(nil)

// Make sure the type types.JSON[json.RawMessage] satisfies database/sql/driver.Valuer
var _ driver.Valuer = *new(types.JSON[json.RawMessage])

// Make sure the type RiverJobState satisfies database/sql.Scanner
var _ sql.Scanner = (*RiverJobState)(nil)

// Make sure the type RiverJobState satisfies database/sql/driver.Valuer
var _ driver.Valuer = *new(RiverJobState)

// Make sure the type pq.StringArray satisfies database/sql.Scanner
var _ sql.Scanner = (*pq.StringArray)(nil)

// Make sure the type pq.StringArray satisfies database/sql/driver.Valuer
var _ driver.Valuer = *new(pq.StringArray)

// Make sure the type uuid.UUID satisfies database/sql.Scanner
var _ sql.Scanner = (*uuid.UUID)(nil)

// Make sure the type uuid.UUID satisfies database/sql/driver.Valuer
var _ driver.Valuer = *new(uuid.UUID)
