// Code generated by BobGen psql v0.34.2. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package modelsnew

import (
	"context"
	"encoding/json"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/lib/pq"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/types"
)

// RiverJob is an object representing the database table.
type RiverJob struct {
	ID           int64                       `db:"id,pk" `
	State        RiverJobState               `db:"state" `
	Attempt      int16                       `db:"attempt" `
	MaxAttempts  int16                       `db:"max_attempts" `
	AttemptedAt  null.Val[time.Time]         `db:"attempted_at" `
	CreatedAt    time.Time                   `db:"created_at" `
	FinalizedAt  null.Val[time.Time]         `db:"finalized_at" `
	ScheduledAt  time.Time                   `db:"scheduled_at" `
	Priority     int16                       `db:"priority" `
	Args         types.JSON[json.RawMessage] `db:"args" `
	AttemptedBy  null.Val[pq.StringArray]    `db:"attempted_by" `
	Errors       null.Val[pq.StringArray]    `db:"errors" `
	Kind         string                      `db:"kind" `
	Metadata     types.JSON[json.RawMessage] `db:"metadata" `
	Queue        string                      `db:"queue" `
	Tags         pq.StringArray              `db:"tags" `
	UniqueKey    null.Val[[]byte]            `db:"unique_key" `
	UniqueStates null.Val[string]            `db:"unique_states" `
}

// RiverJobSlice is an alias for a slice of pointers to RiverJob.
// This should almost always be used instead of []*RiverJob.
type RiverJobSlice []*RiverJob

// RiverJobs contains methods to work with the river_job table
var RiverJobs = psql.NewTablex[*RiverJob, RiverJobSlice, *RiverJobSetter]("", "river_job")

// RiverJobsQuery is a query on the river_job table
type RiverJobsQuery = *psql.ViewQuery[*RiverJob, RiverJobSlice]

type riverJobColumnNames struct {
	ID           string
	State        string
	Attempt      string
	MaxAttempts  string
	AttemptedAt  string
	CreatedAt    string
	FinalizedAt  string
	ScheduledAt  string
	Priority     string
	Args         string
	AttemptedBy  string
	Errors       string
	Kind         string
	Metadata     string
	Queue        string
	Tags         string
	UniqueKey    string
	UniqueStates string
}

var RiverJobColumns = buildRiverJobColumns("river_job")

type riverJobColumns struct {
	tableAlias   string
	ID           psql.Expression
	State        psql.Expression
	Attempt      psql.Expression
	MaxAttempts  psql.Expression
	AttemptedAt  psql.Expression
	CreatedAt    psql.Expression
	FinalizedAt  psql.Expression
	ScheduledAt  psql.Expression
	Priority     psql.Expression
	Args         psql.Expression
	AttemptedBy  psql.Expression
	Errors       psql.Expression
	Kind         psql.Expression
	Metadata     psql.Expression
	Queue        psql.Expression
	Tags         psql.Expression
	UniqueKey    psql.Expression
	UniqueStates psql.Expression
}

func (c riverJobColumns) Alias() string {
	return c.tableAlias
}

func (riverJobColumns) AliasedAs(alias string) riverJobColumns {
	return buildRiverJobColumns(alias)
}

func buildRiverJobColumns(alias string) riverJobColumns {
	return riverJobColumns{
		tableAlias:   alias,
		ID:           psql.Quote(alias, "id"),
		State:        psql.Quote(alias, "state"),
		Attempt:      psql.Quote(alias, "attempt"),
		MaxAttempts:  psql.Quote(alias, "max_attempts"),
		AttemptedAt:  psql.Quote(alias, "attempted_at"),
		CreatedAt:    psql.Quote(alias, "created_at"),
		FinalizedAt:  psql.Quote(alias, "finalized_at"),
		ScheduledAt:  psql.Quote(alias, "scheduled_at"),
		Priority:     psql.Quote(alias, "priority"),
		Args:         psql.Quote(alias, "args"),
		AttemptedBy:  psql.Quote(alias, "attempted_by"),
		Errors:       psql.Quote(alias, "errors"),
		Kind:         psql.Quote(alias, "kind"),
		Metadata:     psql.Quote(alias, "metadata"),
		Queue:        psql.Quote(alias, "queue"),
		Tags:         psql.Quote(alias, "tags"),
		UniqueKey:    psql.Quote(alias, "unique_key"),
		UniqueStates: psql.Quote(alias, "unique_states"),
	}
}

type riverJobWhere[Q psql.Filterable] struct {
	ID           psql.WhereMod[Q, int64]
	State        psql.WhereMod[Q, RiverJobState]
	Attempt      psql.WhereMod[Q, int16]
	MaxAttempts  psql.WhereMod[Q, int16]
	AttemptedAt  psql.WhereNullMod[Q, time.Time]
	CreatedAt    psql.WhereMod[Q, time.Time]
	FinalizedAt  psql.WhereNullMod[Q, time.Time]
	ScheduledAt  psql.WhereMod[Q, time.Time]
	Priority     psql.WhereMod[Q, int16]
	Args         psql.WhereMod[Q, types.JSON[json.RawMessage]]
	AttemptedBy  psql.WhereNullMod[Q, pq.StringArray]
	Errors       psql.WhereNullMod[Q, pq.StringArray]
	Kind         psql.WhereMod[Q, string]
	Metadata     psql.WhereMod[Q, types.JSON[json.RawMessage]]
	Queue        psql.WhereMod[Q, string]
	Tags         psql.WhereMod[Q, pq.StringArray]
	UniqueKey    psql.WhereNullMod[Q, []byte]
	UniqueStates psql.WhereNullMod[Q, string]
}

func (riverJobWhere[Q]) AliasedAs(alias string) riverJobWhere[Q] {
	return buildRiverJobWhere[Q](buildRiverJobColumns(alias))
}

func buildRiverJobWhere[Q psql.Filterable](cols riverJobColumns) riverJobWhere[Q] {
	return riverJobWhere[Q]{
		ID:           psql.Where[Q, int64](cols.ID),
		State:        psql.Where[Q, RiverJobState](cols.State),
		Attempt:      psql.Where[Q, int16](cols.Attempt),
		MaxAttempts:  psql.Where[Q, int16](cols.MaxAttempts),
		AttemptedAt:  psql.WhereNull[Q, time.Time](cols.AttemptedAt),
		CreatedAt:    psql.Where[Q, time.Time](cols.CreatedAt),
		FinalizedAt:  psql.WhereNull[Q, time.Time](cols.FinalizedAt),
		ScheduledAt:  psql.Where[Q, time.Time](cols.ScheduledAt),
		Priority:     psql.Where[Q, int16](cols.Priority),
		Args:         psql.Where[Q, types.JSON[json.RawMessage]](cols.Args),
		AttemptedBy:  psql.WhereNull[Q, pq.StringArray](cols.AttemptedBy),
		Errors:       psql.WhereNull[Q, pq.StringArray](cols.Errors),
		Kind:         psql.Where[Q, string](cols.Kind),
		Metadata:     psql.Where[Q, types.JSON[json.RawMessage]](cols.Metadata),
		Queue:        psql.Where[Q, string](cols.Queue),
		Tags:         psql.Where[Q, pq.StringArray](cols.Tags),
		UniqueKey:    psql.WhereNull[Q, []byte](cols.UniqueKey),
		UniqueStates: psql.WhereNull[Q, string](cols.UniqueStates),
	}
}

var RiverJobErrors = &riverJobErrors{
	ErrUniqueRiverJobPkey: &UniqueConstraintError{s: "river_job_pkey"},

	ErrUniqueRiverJobUniqueIdx: &UniqueConstraintError{s: "river_job_unique_idx"},
}

type riverJobErrors struct {
	ErrUniqueRiverJobPkey *UniqueConstraintError

	ErrUniqueRiverJobUniqueIdx *UniqueConstraintError
}

// RiverJobSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type RiverJobSetter struct {
	ID           omit.Val[int64]                       `db:"id,pk" `
	State        omit.Val[RiverJobState]               `db:"state" `
	Attempt      omit.Val[int16]                       `db:"attempt" `
	MaxAttempts  omit.Val[int16]                       `db:"max_attempts" `
	AttemptedAt  omitnull.Val[time.Time]               `db:"attempted_at" `
	CreatedAt    omit.Val[time.Time]                   `db:"created_at" `
	FinalizedAt  omitnull.Val[time.Time]               `db:"finalized_at" `
	ScheduledAt  omit.Val[time.Time]                   `db:"scheduled_at" `
	Priority     omit.Val[int16]                       `db:"priority" `
	Args         omit.Val[types.JSON[json.RawMessage]] `db:"args" `
	AttemptedBy  omitnull.Val[pq.StringArray]          `db:"attempted_by" `
	Errors       omitnull.Val[pq.StringArray]          `db:"errors" `
	Kind         omit.Val[string]                      `db:"kind" `
	Metadata     omit.Val[types.JSON[json.RawMessage]] `db:"metadata" `
	Queue        omit.Val[string]                      `db:"queue" `
	Tags         omit.Val[pq.StringArray]              `db:"tags" `
	UniqueKey    omitnull.Val[[]byte]                  `db:"unique_key" `
	UniqueStates omitnull.Val[string]                  `db:"unique_states" `
}

func (s RiverJobSetter) SetColumns() []string {
	vals := make([]string, 0, 18)
	if !s.ID.IsUnset() {
		vals = append(vals, "id")
	}

	if !s.State.IsUnset() {
		vals = append(vals, "state")
	}

	if !s.Attempt.IsUnset() {
		vals = append(vals, "attempt")
	}

	if !s.MaxAttempts.IsUnset() {
		vals = append(vals, "max_attempts")
	}

	if !s.AttemptedAt.IsUnset() {
		vals = append(vals, "attempted_at")
	}

	if !s.CreatedAt.IsUnset() {
		vals = append(vals, "created_at")
	}

	if !s.FinalizedAt.IsUnset() {
		vals = append(vals, "finalized_at")
	}

	if !s.ScheduledAt.IsUnset() {
		vals = append(vals, "scheduled_at")
	}

	if !s.Priority.IsUnset() {
		vals = append(vals, "priority")
	}

	if !s.Args.IsUnset() {
		vals = append(vals, "args")
	}

	if !s.AttemptedBy.IsUnset() {
		vals = append(vals, "attempted_by")
	}

	if !s.Errors.IsUnset() {
		vals = append(vals, "errors")
	}

	if !s.Kind.IsUnset() {
		vals = append(vals, "kind")
	}

	if !s.Metadata.IsUnset() {
		vals = append(vals, "metadata")
	}

	if !s.Queue.IsUnset() {
		vals = append(vals, "queue")
	}

	if !s.Tags.IsUnset() {
		vals = append(vals, "tags")
	}

	if !s.UniqueKey.IsUnset() {
		vals = append(vals, "unique_key")
	}

	if !s.UniqueStates.IsUnset() {
		vals = append(vals, "unique_states")
	}

	return vals
}

func (s RiverJobSetter) Overwrite(t *RiverJob) {
	if !s.ID.IsUnset() {
		t.ID, _ = s.ID.Get()
	}
	if !s.State.IsUnset() {
		t.State, _ = s.State.Get()
	}
	if !s.Attempt.IsUnset() {
		t.Attempt, _ = s.Attempt.Get()
	}
	if !s.MaxAttempts.IsUnset() {
		t.MaxAttempts, _ = s.MaxAttempts.Get()
	}
	if !s.AttemptedAt.IsUnset() {
		t.AttemptedAt, _ = s.AttemptedAt.GetNull()
	}
	if !s.CreatedAt.IsUnset() {
		t.CreatedAt, _ = s.CreatedAt.Get()
	}
	if !s.FinalizedAt.IsUnset() {
		t.FinalizedAt, _ = s.FinalizedAt.GetNull()
	}
	if !s.ScheduledAt.IsUnset() {
		t.ScheduledAt, _ = s.ScheduledAt.Get()
	}
	if !s.Priority.IsUnset() {
		t.Priority, _ = s.Priority.Get()
	}
	if !s.Args.IsUnset() {
		t.Args, _ = s.Args.Get()
	}
	if !s.AttemptedBy.IsUnset() {
		t.AttemptedBy, _ = s.AttemptedBy.GetNull()
	}
	if !s.Errors.IsUnset() {
		t.Errors, _ = s.Errors.GetNull()
	}
	if !s.Kind.IsUnset() {
		t.Kind, _ = s.Kind.Get()
	}
	if !s.Metadata.IsUnset() {
		t.Metadata, _ = s.Metadata.Get()
	}
	if !s.Queue.IsUnset() {
		t.Queue, _ = s.Queue.Get()
	}
	if !s.Tags.IsUnset() {
		t.Tags, _ = s.Tags.Get()
	}
	if !s.UniqueKey.IsUnset() {
		t.UniqueKey, _ = s.UniqueKey.GetNull()
	}
	if !s.UniqueStates.IsUnset() {
		t.UniqueStates, _ = s.UniqueStates.GetNull()
	}
}

func (s *RiverJobSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return RiverJobs.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 18)
		if s.ID.IsUnset() {
			vals[0] = psql.Raw("DEFAULT")
		} else {
			vals[0] = psql.Arg(s.ID)
		}

		if s.State.IsUnset() {
			vals[1] = psql.Raw("DEFAULT")
		} else {
			vals[1] = psql.Arg(s.State)
		}

		if s.Attempt.IsUnset() {
			vals[2] = psql.Raw("DEFAULT")
		} else {
			vals[2] = psql.Arg(s.Attempt)
		}

		if s.MaxAttempts.IsUnset() {
			vals[3] = psql.Raw("DEFAULT")
		} else {
			vals[3] = psql.Arg(s.MaxAttempts)
		}

		if s.AttemptedAt.IsUnset() {
			vals[4] = psql.Raw("DEFAULT")
		} else {
			vals[4] = psql.Arg(s.AttemptedAt)
		}

		if s.CreatedAt.IsUnset() {
			vals[5] = psql.Raw("DEFAULT")
		} else {
			vals[5] = psql.Arg(s.CreatedAt)
		}

		if s.FinalizedAt.IsUnset() {
			vals[6] = psql.Raw("DEFAULT")
		} else {
			vals[6] = psql.Arg(s.FinalizedAt)
		}

		if s.ScheduledAt.IsUnset() {
			vals[7] = psql.Raw("DEFAULT")
		} else {
			vals[7] = psql.Arg(s.ScheduledAt)
		}

		if s.Priority.IsUnset() {
			vals[8] = psql.Raw("DEFAULT")
		} else {
			vals[8] = psql.Arg(s.Priority)
		}

		if s.Args.IsUnset() {
			vals[9] = psql.Raw("DEFAULT")
		} else {
			vals[9] = psql.Arg(s.Args)
		}

		if s.AttemptedBy.IsUnset() {
			vals[10] = psql.Raw("DEFAULT")
		} else {
			vals[10] = psql.Arg(s.AttemptedBy)
		}

		if s.Errors.IsUnset() {
			vals[11] = psql.Raw("DEFAULT")
		} else {
			vals[11] = psql.Arg(s.Errors)
		}

		if s.Kind.IsUnset() {
			vals[12] = psql.Raw("DEFAULT")
		} else {
			vals[12] = psql.Arg(s.Kind)
		}

		if s.Metadata.IsUnset() {
			vals[13] = psql.Raw("DEFAULT")
		} else {
			vals[13] = psql.Arg(s.Metadata)
		}

		if s.Queue.IsUnset() {
			vals[14] = psql.Raw("DEFAULT")
		} else {
			vals[14] = psql.Arg(s.Queue)
		}

		if s.Tags.IsUnset() {
			vals[15] = psql.Raw("DEFAULT")
		} else {
			vals[15] = psql.Arg(s.Tags)
		}

		if s.UniqueKey.IsUnset() {
			vals[16] = psql.Raw("DEFAULT")
		} else {
			vals[16] = psql.Arg(s.UniqueKey)
		}

		if s.UniqueStates.IsUnset() {
			vals[17] = psql.Raw("DEFAULT")
		} else {
			vals[17] = psql.Arg(s.UniqueStates)
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s RiverJobSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s RiverJobSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 18)

	if !s.ID.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if !s.State.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "state")...),
			psql.Arg(s.State),
		}})
	}

	if !s.Attempt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "attempt")...),
			psql.Arg(s.Attempt),
		}})
	}

	if !s.MaxAttempts.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "max_attempts")...),
			psql.Arg(s.MaxAttempts),
		}})
	}

	if !s.AttemptedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "attempted_at")...),
			psql.Arg(s.AttemptedAt),
		}})
	}

	if !s.CreatedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if !s.FinalizedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "finalized_at")...),
			psql.Arg(s.FinalizedAt),
		}})
	}

	if !s.ScheduledAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "scheduled_at")...),
			psql.Arg(s.ScheduledAt),
		}})
	}

	if !s.Priority.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "priority")...),
			psql.Arg(s.Priority),
		}})
	}

	if !s.Args.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "args")...),
			psql.Arg(s.Args),
		}})
	}

	if !s.AttemptedBy.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "attempted_by")...),
			psql.Arg(s.AttemptedBy),
		}})
	}

	if !s.Errors.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "errors")...),
			psql.Arg(s.Errors),
		}})
	}

	if !s.Kind.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "kind")...),
			psql.Arg(s.Kind),
		}})
	}

	if !s.Metadata.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "metadata")...),
			psql.Arg(s.Metadata),
		}})
	}

	if !s.Queue.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "queue")...),
			psql.Arg(s.Queue),
		}})
	}

	if !s.Tags.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "tags")...),
			psql.Arg(s.Tags),
		}})
	}

	if !s.UniqueKey.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "unique_key")...),
			psql.Arg(s.UniqueKey),
		}})
	}

	if !s.UniqueStates.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "unique_states")...),
			psql.Arg(s.UniqueStates),
		}})
	}

	return exprs
}

// FindRiverJob retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindRiverJob(ctx context.Context, exec bob.Executor, IDPK int64, cols ...string) (*RiverJob, error) {
	if len(cols) == 0 {
		return RiverJobs.Query(
			SelectWhere.RiverJobs.ID.EQ(IDPK),
		).One(ctx, exec)
	}

	return RiverJobs.Query(
		SelectWhere.RiverJobs.ID.EQ(IDPK),
		sm.Columns(RiverJobs.Columns().Only(cols...)),
	).One(ctx, exec)
}

// RiverJobExists checks the presence of a single record by primary key
func RiverJobExists(ctx context.Context, exec bob.Executor, IDPK int64) (bool, error) {
	return RiverJobs.Query(
		SelectWhere.RiverJobs.ID.EQ(IDPK),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after RiverJob is retrieved from the database
func (o *RiverJob) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = RiverJobs.AfterSelectHooks.RunHooks(ctx, exec, RiverJobSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = RiverJobs.AfterInsertHooks.RunHooks(ctx, exec, RiverJobSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = RiverJobs.AfterUpdateHooks.RunHooks(ctx, exec, RiverJobSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = RiverJobs.AfterDeleteHooks.RunHooks(ctx, exec, RiverJobSlice{o})
	}

	return err
}

// PrimaryKeyVals returns the primary key values of the RiverJob
func (o *RiverJob) PrimaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *RiverJob) pkEQ() dialect.Expression {
	return psql.Quote("river_job", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		return o.PrimaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the RiverJob
func (o *RiverJob) Update(ctx context.Context, exec bob.Executor, s *RiverJobSetter) error {
	v, err := RiverJobs.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *v

	return nil
}

// Delete deletes a single RiverJob record with an executor
func (o *RiverJob) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := RiverJobs.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the RiverJob using the executor
func (o *RiverJob) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := RiverJobs.Query(
		SelectWhere.RiverJobs.ID.EQ(o.ID),
	).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *o2

	return nil
}

// AfterQueryHook is called after RiverJobSlice is retrieved from the database
func (o RiverJobSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = RiverJobs.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = RiverJobs.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = RiverJobs.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = RiverJobs.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o RiverJobSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("river_job", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.PrimaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o RiverJobSlice) copyMatchingRows(from ...*RiverJob) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}

			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o RiverJobSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return RiverJobs.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *RiverJob:
				o.copyMatchingRows(retrieved)
			case []*RiverJob:
				o.copyMatchingRows(retrieved...)
			case RiverJobSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a RiverJob or a slice of RiverJob
				// then run the AfterUpdateHooks on the slice
				_, err = RiverJobs.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o RiverJobSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return RiverJobs.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *RiverJob:
				o.copyMatchingRows(retrieved)
			case []*RiverJob:
				o.copyMatchingRows(retrieved...)
			case RiverJobSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a RiverJob or a slice of RiverJob
				// then run the AfterDeleteHooks on the slice
				_, err = RiverJobs.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o RiverJobSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals RiverJobSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := RiverJobs.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o RiverJobSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := RiverJobs.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o RiverJobSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := RiverJobs.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}
