{
 "title": "Application Metrics Dashboard",
 "tags": [
  "application",
  "metrics"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus", "query": "prometheus" },
   { "name": "loki_datasource", "label": "Loki", "query": "loki" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(${prometheus_datasource}, job)"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(${loki_datasource}, service)"
   }
  ]
 },
 "panels": [
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Server Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 13, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "{service=\"$service\"} !~ `status=4..` !~ `status=5...` !~ `path=/api/v1/health`"
    }
   ]
  },
  {
   "title": "HTTP Error Logs (4xx/5xx)",
   "type": "logs",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 1 },
   "targets": [
    {
     "expr": "{service=\"$service\"} |~ `status=4..` | logfmt |~ `path=/api/v1/health`"
    },
    {
     "expr": "{service=\"$service\"} |~ `status=5..` | logfmt |~ `path=/api/v1/health`"
    }
   ]
  },
  { "title": "HTTP Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "HTTP Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(status_code, route) (rate(http_requests_total{job=\"$job\", route!=\"/api/v1/health\"}[5m]))",
     "legendFormat": "({{route}} {{status_code}})"
    }
   ]
  },
  {
   "title": "Requests In Flight",
   "type": "stat",
   "gridPos": { "h": 16, "w": 3, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_in_flight{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requests (1h)",
   "type": "stat",
   "gridPos": { "h": 16, "w": 3, "x": 15, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{job=\"$job\", route!=\"/api/v1/health\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate (4xx)",
   "type": "stat",
   "gridPos": { "h": 16, "w": 3, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(http_requests_total{job=\"$job\", status_code=\"404\", route!=\"/api/v1/health\"}[5m])) / count(rate(http_requests_total{job=\"$job\", status_code!=\"404\", route!=\"/api/v1/health\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status Codes (1h)",
   "type": "piechart",
   "gridPos": { "h": 16, "w": 3, "x": 21, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status_code) (increase(http_requests_total{job=\"$job\", route!=\"/api/v1/health\"}[1h]))",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "HTTP Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(job) (histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job=\"$job\", route!=\"/api/v1/health\"}[5m])))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "sum by(job) (histogram_quantile(0.5, rate(http_request_duration_seconds_bucket{job=\"$job\", route!=\"/api/v1/health\"}[5m])))",
     "legendFormat": "50th percentile"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{job=\"$job\", route!=\"/api/v1/health\"}[5m])) / sum(rate(http_request_duration_seconds_count{job=\"$job\", route!=\"/api/v1/health\"}[5m]))",
     "legendFormat": "Average"
    }
   ]
  },
  { "title": "Go Runtime Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Go Goroutines & Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{job=\"$job\"}",
     "legendFormat": "Goroutines"
    },
    {
     "expr": "go_threads{job=\"$job\"}",
     "legendFormat": "OS Threads"
    }
   ]
  },
  {
   "title": "Heap Objects",
   "type": "stat",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_memstats_heap_objects{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"$job\"}",
     "legendFormat": "Allocated"
    },
    {
     "expr": "go_memstats_sys_bytes{job=\"$job\"}",
     "legendFormat": "System"
    },
    {
     "expr": "process_resident_memory_bytes{job=\"$job\"}",
     "legendFormat": "Resident"
    }
   ]
  }
 ]
}