name: Integration Tests

# on:
#   push:
#     branches:
#       - 'master'

on:
  push:
    branches:
      - '**'
      - '!master'

  pull_request:
    types:
      - reopened
    branches:
      - '**'
      - '!master'

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v3
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: run
        run: just test-integrations
